stages:
- name: build
  steps:
  - runScriptConfig:
      image: maven:3.6-jdk-8-alpine
      shellScript: |-
        pwd
        ls -al
        mvn install -Dmaven.test.skip=true
        docker build -t myeureka .
        docker tag myeureka:latest 10.10.66.49:9081/sbfx/myeureka:latest
        docker push 10.10.66.49:9081/sbfx/myeureka:latest
- name: 部署
  steps:
  - publishImageConfig:
      dockerfilePath: ./
      buildContext: .
      tag: myeureka:latest
      pushRemote: true
      registry: 10.10.66.49:9081
- name: 部署应用
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
notification:
  recipients:
  - recipient: chenfg@yonyou.com
    notifier: c-4dkhv:n-mzm72
  condition:
  - Changed
