stages:
- name: build
  steps:
  - runScriptConfig:
      image: maven:3.6-jdk-8-alpine
      shellScript: |-
        pwd
        ls -al
        mvn install -Dmaven.test.skip=true
- name: 部署
  steps:
  - publishImageConfig:
      dockerfilePath: dockerfile
      tag: myeureka:latest
      pushRemote: true
      registry: 10.10.66.49:9081
    env:
      PLUGIN_DEBUG: "true"
      PLUGIN_INSECURE: "true"
- name: 部署应用
  steps:
  - applyYamlConfig:
      path: ./deployment.yml
timeout: 60
notification:
  recipients:
  - recipient: chenfg@yonyou.com
    notifier: c-4dkhv:n-mzm72
  condition:
  - Changed
