apiVersion: v1
kind: Service
metadata:
  name: eurekaserver
spec:
  selector:
    app: eurekaserver
  type: NodePort
  ports:
    - protocol: TCP
      nodePort: 32381
      port: 8791
      targetPort: 8791