server:
  port: 8791
spring:
  application:
    name: eurekatest

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
        defalutZone: http://localhost:8791/eureka #因为默认情况下一个eureka-server也是一个eureka-client,所以设置注册eureka为false